version: "3"

services:
  mysql:
    container_name: p_money_manager_db
    image: mysql:8
    environment:
      MYSQL_DATABASE: "p_money_manager_db"
      MYSQLDB_USER: "root"
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: