/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EmailInput: typeof import('./src/components/EmailInput/index.vue')['default']
    PButton: typeof import('./src/components/PButton/index.vue')['default']
    PFooter: typeof import('./src/components/PFooter/index.vue')['default']
    PHeader: typeof import('./src/components/PHeader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
